export const typescriptConfig = {
  compilerOptions: {
    target: "ES2020",
    lib: ["ES2020", "DOM", "DOM.Iterable"],
    module: "ESNext",
    moduleResolution: "bundler",
    jsx: "react-jsx",
    strict: true,
    esModuleInterop: true,
    skipLibCheck: true,
    declaration: true,
    declarationMap: true,
    sourceMap: true,
    noUnusedLocals: true,
    noUnusedParameters: true,
    noFallthroughCasesInSwitch: true,
    isolatedModules: true,
    baseUrl: ".",
    paths: {
      "@lexiwind/core": ["packages/core/src"],
      "@lexiwind/core/*": ["packages/core/src/*"],
      "@lexiwind/react": ["packages/react/src"],
      "@lexiwind/react/*": ["packages/react/src/*"],
      "@lexiwind/history": ["packages/history/src"],
      "@lexiwind/history/*": ["packages/history/src/*"],
      "@lexiwind/table": ["packages/table/src"],
      "@lexiwind/table/*": ["packages/table/src/*"],
      "@lexiwind/code": ["packages/code/src"],
      "@lexiwind/code/*": ["packages/code/src/*"],
      "@lexiwind/slash-command": ["packages/slash-command/src"],
      "@lexiwind/slash-command/*": ["packages/slash-command/src/*"],
      "@lexiwind/toolbar": ["packages/toolbar/src"],
      "@lexiwind/toolbar/*": ["packages/toolbar/src/*"],
      "@lexiwind/mentions": ["packages/mentions/src"],
      "@lexiwind/mentions/*": ["packages/mentions/src/*"],
      "@lexiwind/collapsible": ["packages/collapsible/src"],
      "@lexiwind/collapsible/*": ["packages/collapsible/src/*"],
      "@lexiwind/embeds": ["packages/embeds/src"],
      "@lexiwind/embeds/*": ["packages/embeds/src/*"],
      "@lexiwind/themes": ["packages/themes/src"],
      "@lexiwind/themes/*": ["packages/themes/src/*"],
      "@lexiwind/config-eslint": ["packages/config-eslint/src"],
      "@lexiwind/config-eslint/*": ["packages/config-eslint/src/*"],
      "@lexiwind/config-typescript": ["packages/config-typescript/src"],
      "@lexiwind/config-typescript/*": ["packages/config-typescript/src/*"],
    },
  },
} as const;

export type TypeScriptConfig = typeof typescriptConfig;
